### ISSUE TITLE
مشکل در نصب روی لاراول 11

### ISSUE THREAD

**Issue by aragornq** [shetabit/payment#306] opened 2024-03-27 04:05 UTC
Problem 1
    - shetabit/payment v5.8.0 requires shetabit/multipay ^1.0 -> satisfiable by shetabit/multipay[v1.0, ..., v1.45.0].
    - shetabit/payment v1.0 requires illuminate/support ~5.1 -> found illuminate/support[v5.1.1, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - shetabit/payment[v1.1, ..., v1.2] require illuminate/broadcasting ~5.1 -> found illuminate/broadcasting[v5.1.1, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - shetabit/payment v1.2.1 requires guzzlehttp/guzzle ^6.3 -> found guzzlehttp/guzzle[6.3.0, ..., 6.5.8] but the package is fixed to 7.8.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - shetabit/payment[v1.2.2, ..., v1.2.3, v2.0, ..., v2.2.4] require illuminate/broadcasting >=5.8 <7.0 -> found illuminate/broadcasting[v5.8.0, ..., v5.8.36, v6.0.0, ..., v6.20.44] but these were not loaded, likely because it conflicts with another require.
    - shetabit/payment v2.3 requires illuminate/broadcasting 5.8.*|6.*|7.* -> found illuminate/broadcasting[v5.8.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - shetabit/payment[v2.4, ..., v2.4.8, v3.0.0, ..., v3.0.1] require illuminate/broadcasting ^5.8|^6.0|^7.0 -> found illuminate/broadcasting[v5.8.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - shetabit/payment[v3.1.0, v4.0.0, ..., v4.2.0] require illuminate/broadcasting ^5.0|^6.0|^7.0|^8.0 -> found illuminate/broadcasting[v5.1.1, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - shetabit/payment[v4.2.1, ..., v4.3.3] require illuminate/broadcasting ^5.0|^6.0|^7.0|^8.0|^9.0 -> found illuminate/broadcasting[v5.1.1, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - shetabit/payment[v5.0.0, ..., v5.7.0] require illuminate/broadcasting ^5.0|^6.0|^7.0|^8.0|^9.0|^10.0 -> found illuminate/broadcasting[v5.1.1, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.4] but these were not loaded, likely because it conflicts with another require.
    - shetabit/multipay[v1.0, ..., v1.45.0] require nesbot/carbon ^1.39|^2.0 -> found nesbot/carbon[1.39.0, 1.39.1, 2.0.0, ..., 2.72.3] but the package is fixed to 3.1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires shetabit/payment * -> satisfiable by shetabit/payment[v1.0, ..., v1.2.3, v2.0, ..., v2.4.8, v3.0.0, v3.0.1, v3.1.0, v4.0.0, ..., v4.3.3, v5.0.0, ..., v5.8.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require shetabit/payment:*" to figure out if any version is installable, or "composer require shetabit/payment:^2.1" if you know which you need.

**Comment by khanzadimahdi** [comment] 2024-03-27 11:50
duplicate of https://github.com/shetabit/payment/issues/303

**Closed by khanzadimahdi** 2024-03-27 11:50 UTC
